spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated # 消息发送到交换机会触发回调方法
    publisher-returns: true # 是否开启生产者消息回退功能，队列中的消息不可路由回退到生产者
    listener:
      type: simple
      simple:
        retry:
          enabled: true # 开启消费者重试
          max-attempts: 5 # 最大重试次数，默认为 3 次
          initial-interval: 2000 # 消息的间隔时间 默认为 1 秒
        acknowledge-mode: manual # 手动确认
        default-requeue-rejected: false # 重试次数超过上面的设置之后是否丢失
